@startuml
'https://plantuml.com/object-diagram

class Main {
    +void main()
    +int countLampsInBuilding(Building building)
    +boolean isNormalBuilding(Building building)
}

class Building {
    -ArrayList<Room> rooms
    -int numberOfBathrooms
    -int numberOfFloors
    -boolean isOfficeBuilding

    +Building(ArrayList<Room> rooms, int numberOfBathrooms, int numberOfFloors, boolean isOfficeBuilding)
    +ArrayList<Room> getRooms()
    +int getNumberOfBathrooms()
    +int getNumberOfFloors()
    +boolean isOfficeBuilding()
}

class Room {
    -int numberOfDoors
    -int numberOfLamps
    -int numberOfWindows

    +Room(int numberOfDoors, int numberOfLamps, int numberOfWindows)
    +int getNumberOfDoors()
    +int getNumberOfLamps()
    +int getNumberOfWindows()
}

Main *-- Building
Building *-- Room

@enduml
