@startuml
'https://plantuml.com/object-diagram

class Main {
    +void main()
}

class Car {
    -boolean make «get/set»
    -String model «get/set»
    -int year «get/set»
    -String bodyStyle «get/set»
    -Driver driver «get/set»

    +Car(boolean make, String model, int year, String bodyStyle, Driver driver)
    +@Override String toString()
}
class Driver {
    -String name
    -int age

    +Driver(String name, int age)
    +String getName()
    +void setName(String name)
    +int getAge()
    +void setAge(int age)
    +@Override String toString()
}

Main *- Car
Car *- Driver

@enduml
